[build]
  command = "npm run build"
  functions = ".netlify/functions"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PRIVATE_TARGET = "server" # Force cache clear Sun Aug  3 11:29:35 EDT 2025
